### ISSUE TITLE
DBC file ?

### ISSUE THREAD

**Issue by tuan97ta** [uhi22/IoniqMotorCAN#1]
I want to know, where did you get the DBC file from?

**Comment by uhi22** [comment]
The base is from https://github.com/commaai/opendbc. By looking on the raw trace data, found out additional signals and added them by hand.

**Comment by tuan97ta** [comment]
Thanks pro, I wonder if this repo is available for Hyundai Ioniq 5?

**Comment by uhi22** [comment]
I'm not aware of such a database. If you find it, I propose that you add it to the opendbc project. Thanks.
